window.$ = window.jQuery = require("jquery");

// require("../../node_modules/datatables.net/js/jquery.dataTables");
// require("../../node_modules/datatables.net-bs4/js/dataTables.bootstrap4");
// require("../../node_modules/datatables.net-responsive/js/dataTables.responsive");
// require("../../node_modules/datatables.net-responsive-bs4/js/responsive.bootstrap4");
// require("../../node_modules/datatables.net-buttons/js/dataTables.buttons");
// require("../../node_modules/datatables.net-buttons-bs4/js/buttons.bootstrap4");
// require("../../node_modules/jszip/dist/jszip");
// require("../../node_modules/pdfmake/build/pdfmake");
// require("../../node_modules/pdfmake/build/vfs_fonts");
// require("../../node_modules/datatables.net-buttons/js/buttons.html5");
// require("../../node_modules/datatables.net-buttons/js/buttons.print");
// require("../../node_modules/datatables.net-buttons/js/buttons.colVis");
require("jszip");
require("pdfmake");
require("datatables.net-bs4");
require("datatables.net-buttons-bs4");
require("datatables.net-buttons/js/buttons.colVis.js");
require("datatables.net-buttons/js/buttons.html5.js");
require("datatables.net-buttons/js/buttons.print.js");
require("datatables.net-datetime");
require("datatables.net-responsive-bs4");
require("datatables.net-scroller-bs4");